### ISSUE TITLE
Let's talk about the next release

### ISSUE THREAD

**Issue by celicoo** [celicoo/docli#10]
<p align="center">
  <img alt="Super Docli" src="https://i.imgur.com/bcvDfRH.jpg" width="250px"/>
</p>

The next release will be the version **2.0.0**. I want to push the development of the subcommands feature due to the most significant feedback I've received:

> Docli should allow nested commands, what's the point otherwise?

Quite frankly, I agree! Docli can't compete with other Go libraries at the same level because of this significant disadvantage.

## The current API 👎

Docli was designed to allow embedded structs to provide a way to group related arguments and create abstractions like `commands` and `flags`:

```go
package main

import (
	"log"

	"github.com/celicoo/docli"
)

var doc = `
Usage: terraform [--version] [--help] <command> [args]

...

Common commands:
    apply              Builds or changes infrastructure
    console            Interactive console for Terraform interpolations
`

type Terraform struct {
	CommonCommands
}

type CommonCommands struct {
	Apply,
	Console bool
}

func main() {
	args, err := docli.Parse(doc)
	if err != nil {
		log.Fatal(err)
	}

	var terraform Terraform
	args.Bind(&terraform)

	if terraform.CommonCommands.Apply {
		// ...
	} else if terraform.CommonCommands.Console {
		// ...
	}
}
```

The problems with this approach are obvious now:

* The program's complexity grows proportionally to the number of arguments, making it harder to test, maintain and even understand it.
* Misplaced responsibility - validation and parsing errors return on the same call
* Weird API - `docli.Parse(doc string) (Args, error)`

## The new API 👍

The new API aims to solve the problems pointed above, add the `subcommands` feature while preserving the simple API.

**1st change:** the function `Parse(doc string) (Args, error)` is going to be replaced with the function `Args() Args`:

```go
var c MyCommand
args := docli.Args()
args.Bind(&c)
```

The second returning value (error) is going to be removed. See **2nd** and **3rd** changes to understand the reason.

**2nd change:** the struct passed to `Bind` will need to implement the `Command` interface:

```go
type command interface {
	// Doc returns the doc string of the [command].
	Doc() string

	// Run is called if the bind succeeds.
	Run()

	// Help is called when a user calls help [command].
	Help()

	// Error is called when a user uses the [command] wrongly.
	Error(error)
}
```

**3rd change:** parsing errors will panic.

> But wait, what about the subcommands feature?

The concrete `command` type can have fields that are themselves concrete `Commands`. You can check a simple example [here](https://github.com/celicoo/docli/tree/feature/examples/examples/git) if you didn't get it.

## Feedback

Please don't hesitate to comment on this Issue. I will love to know your thoughts about the changes that are coming.

**Comment by justinfx** [comment]
I've got a couple questions.
On that first api change:
```
docli.Args(...).Bind(&terraform)
```
Does this imply that it operates on a global state? Or is there going to be a parser instance that you configure, parse, and bind?

For the second change with the Command interface, how will it receive its args and options that were passed. The interface doesn't imply where it would receive that via the run(). 

Lastly, I still don't understand how flags are documented and typed. For instance, how would one define the documentation and type for "program command --foo str"? This is an existing question for the v1 release since none of the examples show this.

**Comment by celicoo** [comment]
Good questions @justinfx.

> Does this imply that it operates on a global state? Or is there going to be a parser instance that you configure, parse, and bind?

It's a global (and internal) parser. You won't have to configure anything besides the doc string and the concrete Command type.

> For the second change with the Command interface, how will it receive its args and options that were passed. The interface doesn't imply where it would receive that via the run().

The `Args` and `Bind` functions will only have to be called on the main function of the program's entry point, after that Docli will traverse through the fields of the concrete `Command`, assigning values if the field has a primitive type, or pulling the (and starting the same process) doc string if the field implements the `Command` interface.

> I still don't understand how flags are documented and typed. For instance, how would one define the documentation and type for "program command --foo str"? This is an existing question for the v1 release since none of the examples show this.

The **v1**  only understands `arguments`, but they are powerful! You can create abstractions like `flags` and `commands` using embedded interfaces:

```go
package main

import (
	"fmt"
	"log"

	"github.com/celicoo/docli"
)

var doc = `
usage: my-cli [...<args>]

Commands:
  command    description for the command.

Flags:
  -f, --foo  description for the foo flag.
`

type MyCLI struct {
	Commands
	Flags
}

type Commands struct {
	Command bool
}

type Flags struct {
	Foo string
}

func main() {
	args, err := docli.Parse(doc)
	if err != nil {
		log.Fatal(err)
	}
	var myCLI MyCLI
	args.Bind(&myCLI)

	if myCLI.Commands.Command {
		fmt.Println(myCLI.Flags.Foo)
	}
}
```

If you run `go run main.go command --foo=str` on the example above you will see the `str`  printed on your terminal, but that's too hacky, both arguments are global. You can compare the example above with the following example, where the `--foo` argument belongs to the `create` subcommand:

```go
// cmd/main.go
package main

import (
	"fmt"

	"github.com/celicoo/docli"
	"github.com/celicoo/docli/examples/v2/my-program2/create"
)

// doc is the help message of the main command.
var doc = `
Usage: my-command2 <command> [args]

Description about my-command2.

Subcommands:
    create  description of my subcomand here.
`

// Command represents the main command.
type Command struct {
	Create create.Command
}

// Doc returns the doc string of the main command.
func (c *Command) Doc() string {
	return doc
}

// Run is called when the user calls the main command on the command-line.
func (c *Command) Run() {
	fmt.Println(doc)
}

// OnError is called when some unexpected error happens, e.g. the user
// passes an invalid argument for the main command.
func (c *Command) OnError(err error) {
	// Handle errors of the main command here.
}

func main() {
	var c Command
	docli.Args().Bind(&c)
}
```

```go
// cmd/create/create.go
package create

// doc is the help message of the create subcommand.
var doc = `
Usage: my-command2 create [...<args>]

Description about the create subcommand.

Flags:
    -f, --foo  description of foo flag.
`

// Command represents the create subcommand.
type Command struct {
	Flags
}

// Flag represents the possible flags of the create subcommand.
type Flags struct {
	Foo string
}

// Doc returns the doc string of the create subcommand.
func (c *Command) Doc() string {
	return doc
}

// Run is called when the user calls the create subcommand on the command-line.
func (c *Command) Run() {
	// You can access the values here, e.g. c.Flags.Foo
}

func (c *Command) OnError(err error) {
	// Handle errors of the create subcommand here.
}
```

If you have any other questions, let me know.

**Comment by justinfx** [comment]
Thanks for that extra example. I think it was a missing piece in understanding what your current implementation provides. Honestly, I had to look over at the docopt project to understand how it expresses flags, and then deduce that you bind them to the type defined on the bound concrete struct.

**Comment by celicoo** [comment]
@justinfx no problem, it's definitely my pleasure, and I agree with you, this example was missing.

**Comment by celicoo** [comment]
This feature should be released in the next days.
