### ISSUE TITLE
docli.dev seems to be dead?

### ISSUE THREAD

**Issue by viveklak** [celicoo/docli#11]
## Description

Can't seem to resolve `docli.dev` anymore.

## Expected behavior
`docli.dev` works.

## Actual behavior
`docli.dev` doesn't resolve
`** server can't find docli.dev: SERVFAIL`

## Your environment

* Version used:
* Link to your project:

**Comment by celicoo** [comment]
@viveklak thank you for letting me know!

I changed my virtual credit card and forgot to update it on AWS, so they suspended my account 🤣.

**Comment by celicoo** [comment]
@viveklak all good now.
